---
- name: Create user tim
  hosts: all
  become: true

  tasks:
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'DEVELOPMENT_SERVER_SSH_PUBLIC_KEY') }}' is the DEVELOPMENT_SERVER_SSH_PUBLIC_KEY environment variable."
    - name: Create user tim
      user:
        name: tim 
        state: present
    - name: Create .ssh folder
      file:
        path: ~tim/.ssh
        state: directory
        owner: tim
        group: tim
        mode: 0700
    - name: Upload SSH key
      copy:
        content: "{{lookup('ansible.builtin.env', 'DEVELOPMENT_SERVER_SSH_PUBLIC_KEY')}}"
        dest: ~tim/.ssh/authorized_keys
        owner: tim
        group: tim
        mode: 0600